# Generated by Django 4.2.11 on 2024-04-25 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pongrooms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rooms',
        ),
    ]
