networks:
  transcendance :
    name : transcendance

services :
  nginx :
    container_name : nginx
    build : ./nginx/
    ports :
      - 8000:80
    networks :
       - transcendance
    volumes:
      - ../frontend:/var/www/frontend

  django :
    container_name : django
    build : ./django
    networks :
       - transcendance
    volumes:
      - ../frontend:/var/www/frontend
      - ../backend:/var/www/backend