networks:
  transcendance :
    name : transcendance

services :
  nginx :
    container_name : nginx
    build : ./nginx/
    ports :
      - 8000:80
    networks :
       - transcendance
    volumes:
      - ../frontend:/var/www/frontend

  django :
    container_name : django
    build : ./django
    networks :
       - transcendance
    volumes:
      - ../frontend:/var/www/frontend
      - ../backend:/var/www/backend
    environment:
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@gmail.com
      - DJANGO_SUPERUSER_USERNAME=admin

  postgres_db :
    container_name : postgres_db
    image : postgres:15
    environment :
      - POSTGRES_USER=django
      - POSTGRES_PASSWORD=django
      - POSTGRES_DB=transcendence_db
    networks :
      - transcendance
    